export const FETCHED_ALL_PHONES = "FETCHED_ALL_PHONES";
export const REQUESTED_ALL_PHONES = "REQUESTED_ALL_PHONES";
export const REQUESTED_ALL_PHONES_SUCCEEDED = "REQUESTED_ALL_PHONES_SUCCEEDED";
export const REQUESTED_ALL_PHONES_FAILED = "REQUESTED_ALL_PHONES_FAILED";

export const FETCHED_ONE_PHONE = "FETCHED_ONE_PHONE";
export const REQUESTED_ONE_PHONE = "REQUESTED_ONE_PHONE";
export const REQUESTED_ONE_PHONE_SUCCEEDED = "REQUESTED_ONE_PHONE_SUCCEEDED";
export const REQUESTED_ONE_PHONE_FAILED = "REQUESTED_ONE_PHONES_FAILED";

export const GET_MORE_PHONES = "GET_MORE_PHONES";

export const CHANGE_USER_AND_TOKEN = "CHANGE_USER_AND_TOKEN";
export const LOG_OUT = "LOG_OUT";
export const ADD_INITIAL_PHONES = "ADD_INITIAL_PHONES";
export const ADD_NEW_PHONE = "ADD_NEW_PHONE";
export const ALL_FAVORITE_PHONES = "ALL_FAVORITE_PHONES";
export const UPDATE_USER = "UPDATE_USER";
export const SET_INITIAL_FAVORITE = "SET_INITIAL_FAVORITE";
export const REMOVE_PHONE = "REMOVE_PHONE";
export const WITH_FILTERS = "WITH_FILTERS";